### ISSUE TITLE
RuntimeError: set_num_threads expects an int, but got str

### ISSUE THREAD

**Issue by ZeWLi** [fteufel/signalp-6.0#24]
Hi fteufel,
   Signalp-6.0 is an outstanding software for signal peptide prediction, and I ran this software with parameter: --torch_num_thread 25, but it raised an error
```
Traceback (most recent call last):
  File "/data/conda_envs/signalp6/bin/signalp6", line 33, in <module>
    sys.exit(load_entry_point('signalp6==6.0+h', 'console_scripts', 'signalp6')())
  File "/data/conda_envs/signalp6/lib/python3.7/site-packages/signalp6-6.0+h-py3.7.egg/signalp/__init__.py", line 6, in predict
    main()
  File "/data/conda_envs/signalp6/lib/python3.7/site-packages/signalp6-6.0+h-py3.7.egg/signalp/predict.py", line 144, in main
    torch.set_num_threads(args.torch_num_threads)
RuntimeError: set_num_threads expects an int, but got str
```
Then I checked  line 144 in ```predict.py```
```
torch.set_num_threads(args.torch_num_threads)
```
and I found the error was raised because parameter was passed with a string format, then I use ```int``` function like that
```
torch.set_num_threads(int(args.torch_num_threads))
```
and it worked. So I wonder you can fix this problem in the later version of Signalp-6.0. Thanks for the useful tool again!

Best,
Zewei

**Comment by fteufel** [comment]
Thanks for reporting @ZeWLi ! 
Indeed, the correct type cast is missing here. I'll include the fix in the next update.

Thank you for the kind words!
Felix

**Comment by JChristopherEllis** [comment]
Hi, I tried the fix described above by changing predict.py to torch.set_num_threads(int(args.torch_num_threads)) but I still get the same error. What did I do wrong?

**Comment by fteufel** [comment]
fixed in 6.0i release
